### ISSUE TITLE
Review forum and research techniques

### ISSUE THREAD

**Issue by rupchap** [rupchap/IRDM2016#2]
- [ ] create a list of approaches to try with brief detail / link to forum discussion
- [ ] review linked papers for any approaches there too.

**Comment by artemisdampa** [comment]
arima or neural nets?

**Comment by artemisdampa** [comment]
I've been doing some research and found a paper from a team that participated in the competition explaining their technique (gradient boosting) http://robjhyndman.com/papers/kaggle-competition.pdf
I also found this paper http://pierrepinson.com/31761/Literature/hong2014.pdf which talks about the specific competition but it claims that arima might not be as promising as other approaches.
The following were the winning techniques in the competition:
1. Multiple linear regression, SVD
2. Multiple linear regression, gradient boosting, Gaussian process regression
3. Semi-parametric regression, splines
4. Non-parametric additive models, gradient boosting

**Comment by rupchap** [comment]
Thanks Artemis - this is a handy paper.  I'm going to try and replicate Tao's benchmark
