### ISSUE TITLE
Create basic code to load and process data ready for analysis

### ISSUE THREAD

**Issue by rupchap** [rupchap/IRDM2016#3]
there's already some initial code in git

**Comment by rupchap** [comment]
@artemisdampa I've streamlined the processing code I had before and uploaded as processdata.py.

feel free to edit or replace!

BTW - I'm using python 2.7 is that okay with you [also @meganemartinez ?]

**Comment by artemisdampa** [comment]
@rupchap thanks a lot! I've installed python 3 but i guess the major difference is the print command. I hope we won't be having compatibility problems

**Comment by meganemartinez** [comment]
I'm also using python 2.7

**Comment by rupchap** [comment]
@artemisdampa I've done some more tweaking on this - see 'processandmergedata.py'.
I think this does the basics.
timeseries data are not yet split out into discrete features.
also haven't yet incorporated US holiday data.

**Comment by artemisdampa** [comment]
@rupchap won't we use year, month, day, hour as different variables? do you think it's better to have them as one feature?

**Comment by rupchap** [comment]
I think probably both.  We’ll definitely want to split out hour and day of week (I expect rather than day of month) as features.
date time might be useful too.

Better to have a surfeit of features I think…

**Comment by meganemartinez** [comment]
Is processdata.py supposed to return 'datetime' in format yyyy-mm-dd hh:mm:ss ? @rupchap

**Comment by rupchap** [comment]
I’ve moved on to ‘processandmergedata.py https://github.com/rupchap/IRDM2016/blob/master/code/processandmergedata.py’ to do the processing.
This relies on pandas to pass the date time fields, so returns as a datetime data type I think - can probably be cast to a string in any format
but there will also be commands to pull out the various components [day, hour] etc. 

For example:

# Add categorical time variables

def addTimeDateCategories(df):
    df['summer'] = df['datetime'].dt.month.isin(range(4, 10))
    df['hour'] = df['datetime'].dt.hour
    return df
