### ISSUE TITLE
create code to build a baseline arima model

### ISSUE THREAD

**Issue by rupchap** [rupchap/IRDM2016#4]

**Comment by artemisdampa** [comment]
http://www.r-bloggers.com/backcasting-in-r/
http://robjhyndman.com/hyndsight/backcasting/
http://support.sas.com/documentation/cdl/en/etsug/65545/HTML/default/viewer.htm#etsug_ssm_examples03.htm

**Comment by artemisdampa** [comment]
http://support.sas.com/documentation/cdl/en/etsug/65545/HTML/default/viewer.htm#etsug_ssm_examples03.htm

**Comment by artemisdampa** [comment]
very interesting - python model http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.tsa.arima_model.ARIMA.html
plus a paper on it http://conference.scipy.org/proceedings/scipy2011/pdfs/statsmodels.pdf
this discussion might also be useful http://stackoverflow.com/questions/22770352/auto-arima-equivalent-for-python

**Comment by artemisdampa** [comment]
plus a paper on it http://conference.scipy.org/proceedings/scipy2011/pdfs/statsmodels.pdf

**Comment by artemisdampa** [comment]
this discussion might also be useful http://stackoverflow.com/questions/22770352/auto-arima-equivalent-for-python

**Comment by rupchap** [comment]
another link from @meganemartinez on another issue [which I'm closing as a dupe]
http://www.analyticsvidhya.com/blog/2016/02/time-series-forecasting-codes-python/

**Comment by meganemartinez** [comment]
Creates first model under arima.py. Needs to be automed for every missing value ranges and every zones. Provides interresting charts

**Comment by rupchap** [comment]
Hi Megane,
this looks good.  I've just made a tiny change to point to new location of source data files.
I get the first few charts but then I get an error:

``` python
Traceback (most recent call last):
  File "/home/rupchap/irdm/IRDM2016/code/arima.py", line 144, in <module>
    test_stationarity(ts_log_diff)
  File "/home/rupchap/irdm/IRDM2016/code/arima.py", line 18, in test_stationarity
    rolmean = ts.rolling(window=12,center=False).mean()
  File "/home/rupchap/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 2360, in __getattr__
    (type(self).__name__, name))
AttributeError: 'Series' object has no attribute 'rolling'
```

it looks like '.rolling' isn't recognised when applied to a series.
Is there a missing import or something?

**Comment by meganemartinez** [comment]
Hum, it might come from the version of pandas, I have pandas 0.18 installed and the method I used first was deprecated so I upgraded to the new one. I guess I should put back the previous method for rolling.

**Comment by rupchap** [comment]
Ah.  mine is 0.17.1 - I'll update

**Comment by rupchap** [comment]
That did it, thanks.
Those ACF/PACF charts are interesting.
Clearly 12 month seasonality as we'd expect.
and strong -1 autocorrelation.  maybe -2 too?

**Comment by rupchap** [comment]
no, no -2  -i'm misreading the scale

**Comment by rupchap** [comment]
@meganemartinez what do you think about using arima to forecast temperatures for the missing week at the end of the time series?  and then feeding this in to use for the load forecasting?

Generation of forecast temps is mentioned in hong's paper.  It sounds like most teams did naive things like taking averages of previous days - using arima would represent a definite improvement (in technique at least!) on the previous work...

**Comment by meganemartinez** [comment]
It's a good  idea in theory although I'm not sure how good the results would be. For the loads arima is not working very well so far, there is no real variation in the predictions that are merely linear  unlike the data we have.

**Comment by meganemartinez** [comment]
So I implemented some arima code on R as well to see if the results were better but there aren't. The first few values show some variations but then they remain linear although there is clearly a 24h seasonality. 
Predicting the missing temperature values with arima would be worse than with a naive approach!

**Comment by meganemartinez** [comment]
The arima model can't go through all the predictions for all the zones since one model doesn't fit all the corresponding time series. R has a method to find the best arima model for a given time serie but I can't manage to make it work from Python at the moment.

**Comment by rupchap** [comment]
I think we can have a mixed model with python and R can't we?

**Comment by artemisdampa** [comment]
I don't think they won't accept it so i think it's fine like that

**Comment by rupchap** [comment]
btw @meganemartinez - if things seem quiet here, it's because Artemis and I are mostly using slack...

**Comment by meganemartinez** [comment]
I know, I should check it more often :/
I'm almost done wih arima for both loads and the missing temperatures. I will upload everything tonight.

**Comment by meganemartinez** [comment]
I updated arima.py, in the end I'm using a R package pypeR (needs to have R install as well). I also uploaded processTemp.py and arimaTemp.py for processing temperatures data and predicting the missing values. The output is in data/arimaTemp.csv

**Comment by rupchap** [comment]
Hi Megane.  The file arimaTemp.csv included duplicate row headers - rows headers were being included at the top of each batch of records for each temperature station.  I've removed for now, as they cause problems when trying to use data elsewhere.  But if you have time could you take a quick look at the generating code?

**Comment by meganemartinez** [comment]
Sorry about that! I fixed it now.

**Comment by rupchap** [comment]
Ta!
