### ISSUE TITLE
create outline for a report

### ISSUE THREAD

**Issue by rupchap** [rupchap/IRDM2016#6]

**Comment by rupchap** [comment]
latex?

**Comment by artemisdampa** [comment]
I think latex!

**Comment by rupchap** [comment]
just uploaded template file

**Comment by rupchap** [comment]
@meganemartinez @artemisdampa 
folks - I guess we'd better wrap up all our code this evening, as far as possible, so we can focus on report stuff for the next couple of days.
How about a 'hang out' at say 10.30 tomorrow morning?

**Comment by meganemartinez** [comment]
Ok for 10.30 (11.30 here) tomorrow morning!
