### ISSUE TITLE
create baseline regression model

### ISSUE THREAD

**Issue by rupchap** [rupchap/IRDM2016#8]

**Comment by rupchap** [comment]
I've just pushed a very basic linear regression model
just uses temperature readings to predict load.
currently no incorporation of time element; amongst other shortcomings.
but it does run!

**Comment by rupchap** [comment]
I've just uploaded some more on this.
it now _almost_ replicates Tao's baseline model [I didn't notice that he combines Day and Hour into one composite feature, so will have to introduce that].

It also now reports a WRMS score - which is the metric used on the kaggle forum.  We get a score of 107761.60176 which is about middle of the table.  Although bear in mind that we are cheating here by using actual temperature readings for the last week.

Next steps on this:
1. tidy up code
2. tidy up last mismatch to Tao's baseline model (1. use day*hour, 2. use estimated temperature readings).
3. baseline this benchmark model, then see if any tweaks can improve it further.
4. could do with generating some charts - I see both of you have been doing this on your elements

There are several suggestions for improvement in Tao's paper, some of which will hopefully be doable.
As mentioned before I think it would also be good to incorporate (or experiment with) including arima based temperature forecasts.  Although I see you've had trouble getting useful output, @meganemartinez.  Even if it ends up not enhancing the error metric on the model, I think we might still experiment with this as it would genuinely be adding some sophistication beyond what others have done - even if we end up saying it hasn't helped!

**Comment by artemisdampa** [comment]
I couldn't agree more! Well done Rupert. I will try to work on incorporating the day and hour combo and I will also try to think of any other features that could improve it. I could also replicate and integrate the code I've implemented for plotting deviance and feature importance if it sounds useful

**Comment by rupchap** [comment]
Thanks Artemis,  I'm having a go at doing the day/hour combo now - so let's not overlap on that.
But if you can think about plotting and feature importance that would be great - I think those are going to be really powerful for the report...

**Comment by rupchap** [comment]
by the way, the aim when finished is to replicate the model Tao has here:
http://repository.lib.ncsu.edu/ir/bitstream/1840.16/6457/1/etd.pdf   page 90.

**Comment by artemisdampa** [comment]
@rupchap thanks for telling me. I'll do the plotting tonight and upload.

**Comment by rupchap** [comment]
Thanks @artemisdampa , I've just uploaded with those final features included.
We get a score of 78150.17244 now, which is a bit ridiculous - would have been in the top 10% on kaggle.

I hope that's just because we're using correct temperature data (which the kagglers didn't have access to) rather than a bug in my code!

**Comment by rupchap** [comment]
+1 for the variable importance stuff @artemisdampa - looks great!
